# Generated by Django 2.1.3 on 2018-11-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='zone',
            field=models.CharField(max_length=10, null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='train',
            name='distance',
            field=models.IntegerField(null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='train',
            name='type',
            field=models.CharField(max_length=5, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='train',
            name='zone',
            field=models.CharField(max_length=10, null=True, verbose_name='Zone'),
        ),
    ]
