# Generated by Django 2.1.3 on 2018-11-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181103_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='train',
            name='return_train',
            field=models.CharField(max_length=15, verbose_name='Return Train'),
        ),
    ]
