# Generated by Django 2.1.3 on 2018-11-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20181103_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='return_train',
            field=models.CharField(max_length=15, null=True, verbose_name='Return Train'),
        ),
    ]
