# Generated by Django 2.1.3 on 2018-11-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20181103_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure',
            field=models.CharField(max_length=8, null=True, verbose_name='Departure'),
        ),
    ]
