# Generated by Django 2.1.3 on 2018-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20181108_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat_chart',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
