# Generated by Django 2.1.3 on 2018-11-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0013_auto_20181108_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=20, verbose_name='Name')),
                ('type', models.CharField(max_length=2, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_booking', to='book.Seat_Chart')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_bookings', to='book.Station')),
                ('dest_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_schedules', to='book.Schedule')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bookings', to='book.Station')),
                ('source_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_schedules', to='book.Schedule')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_booking', to='book.Train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
