# Generated by Django 2.1.3 on 2018-11-10 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_tickets', to='book.Seat_Chart'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_tickets', to='book.Station'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dest_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_schedule_tickets', to='book.Schedule'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tickets', to='book.Station'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_schedule_tickets', to='book.Schedule'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tickets', to='book.Train'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
