# Generated by Django 2.1.3 on 2018-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20181110_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fare',
            field=models.IntegerField(default=100, verbose_name='Fare'),
            preserve_default=False,
        ),
    ]
